services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:433
    volumes:
      - type: bind
        source: ./nginx/configs/dev.rolytics.conf
        # source: ./nginx/configs/rolytics.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
      - type: bind
        source: ./nginx/html
        target: /var/www/html
        read_only: true
    depends_on:
      - api
      - ui
    networks:
      - rolytics

  api:
    image: node:latest
    container_name: api
    build:
      context: .
      dockerfile: ./packages/api/Dockerfile
    ports:
      - 5000:5000
    networks:
      - rolytics

  ui:
    image: node:latest
    container_name: ui
    build:
      context: .
      dockerfile: ./packages/ui/Dockerfile
    ports:
      - 3000:3000
    networks:
      - rolytics

networks:
  rolytics:   # This defines the rolytics network
    driver: bridge  # Optional, the default driver is bridge