name: deploy

on:
  workflow_run:
    workflows: ["build"]
    branches: [main]
    types: [completed]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/b-smyers/rolytics
            git pull origin main

            export SESSION_SECRET=${{ secrets.SESSION_SECRET }}
            export JWT_API_KEY_SECRET=${{ secrets.JWT_API_KEY_SECRET }}
            
            docker-compose pull
            docker-compose down
            docker-compose up -d --no-deps --remove-orphans
